### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by edernucci**
Adding support for Brazilian Portuguese language.

### CODE REVIEW

**Comment by john681611** [comment]
This looks good but I hate to be a pain and say I've recently added a few more lines if you can quicky sort them then we are all good:
https://github.com/akaAgar/briefing-room-for-dcs/commit/3b7ebd9d829209f381a725220718b16afa195bce

**Comment by edernucci** [comment]
No probs, changes done.

**Comment by john681611** [comment]
Sorry I just finished adding a feature can you add 2 last times (I promise not to add any more until after its merged.)

**Comment by john681611** [comment]
All merged will be out in the next Beta patch that you very much

**Pull request merged**
